version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  target-branch: develop
  assignees:
  - jonfairbanks
  versioning-strategy: increase
  ignore:
  - dependency-name: "@testing-library/user-event"
    versions:
    - 13.1.5
    - 13.1.6
    - 13.1.7
  - dependency-name: react-editor-md
    versions:
    - 1.0.28
  - dependency-name: react-scripts
    versions:
    - 4.0.3
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: lodash
    versions:
    - 4.17.20
